/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersNameImport } from './routes/users/$name'
import { Route as HerosIdImport } from './routes/heros/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const HerosIndexLazyImport = createFileRoute('/heros/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const HerosIndexLazyRoute = HerosIndexLazyImport.update({
  path: '/heros/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heros/index.lazy').then((d) => d.Route))

const UsersNameRoute = UsersNameImport.update({
  path: '/users/$name',
  getParentRoute: () => rootRoute,
} as any)

const HerosIdRoute = HerosIdImport.update({
  path: '/heros/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/heros/$id': {
      id: '/heros/$id'
      path: '/heros/$id'
      fullPath: '/heros/$id'
      preLoaderRoute: typeof HerosIdImport
      parentRoute: typeof rootRoute
    }
    '/users/$name': {
      id: '/users/$name'
      path: '/users/$name'
      fullPath: '/users/$name'
      preLoaderRoute: typeof UsersNameImport
      parentRoute: typeof rootRoute
    }
    '/heros/': {
      id: '/heros/'
      path: '/heros'
      fullPath: '/heros'
      preLoaderRoute: typeof HerosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  HerosIdRoute,
  UsersNameRoute,
  HerosIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/heros/$id",
        "/users/$name",
        "/heros/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/heros/$id": {
      "filePath": "heros/$id.tsx"
    },
    "/users/$name": {
      "filePath": "users/$name.tsx"
    },
    "/heros/": {
      "filePath": "heros/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
