/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HerosLazyImport = createFileRoute('/heros')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HerosLazyRoute = HerosLazyImport.update({
  path: '/heros',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heros.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/heros': {
      id: '/heros'
      path: '/heros'
      fullPath: '/heros'
      preLoaderRoute: typeof HerosLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  HerosLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/heros"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/heros": {
      "filePath": "heros.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
